name: Format Lint

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions: 
  contents: read

jobs:
  build:
    permissions: 
      contents: read  # Job-level permissions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Prettier
      run: |
        npm install -g prettier
    - name: Module 1 - nodejs-intro
      run: |
        cd nodejs-intro
        npm install
        npm run format
        npm run lint
    - name: Module 1 - nodejs-intro-esm
      run: |
        cd nodejs-intro-esm
        npm install
        npm run format
        npm run lint        
    
    - name: Module 2 - node-dependencies
      run: |
        cd node-dependencies
        npm install
        npm run format
        npm run lint

    - name: Module 3 - nodejs-debug
      run: |
        cd node-dependencies
        npm install
        npm run format
        npm run lint

    - name: Module 4 - nodejs-files
      run: |
        cd nodejs-files
        npm install
        npm run format
        npm run lint

    - name: Module 5 - nodejs-http
      run: |
        cd nodejs-http
        npm install
        npm run format
        npm run lint

    - name: Module 6 - nodejs-route
      run: |
        cd nodejs-route
        npm install
        npm run format
        npm run lint   

    - name: Docs - async iterators
      # In JS Dev Center
      run: |
        cd async-iterators
        npm install
        npm run format
        npm run lint   